language: python

python:
    - 2.7

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run `which trial` lisa/server

after_success:
  - coveralls

services:
  - mongodb

notifications:
  irc: "irc.freenode.net#lisa-project"
  
branches:
  only:
    - master
