language: python

python:
    - 2.7
env:
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==13.2.0 PYOPENSSL=PyOpenSSL

install:
  - pip install $TWISTED
  - 'test -n "$PYOPENSSL" && pip install $PYOPENSSL || true'
  - pip install -r install/requirements.txt

script:
  - trial lisa/server

services:
  - mongodb

notifications:
  irc: "irc.oftc.net#lisa"

branches:
  only:
    - master
