language: python

python:
    - 2.7

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - touch /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/lisa/__init__.py #trial bug with namespaces ticket #5318

script:
  - `which yes` | env PYTHONPATH=. coverage run --source=lisa `which trial` lisa.server

after_success:
  - coveralls

services:
  - mongodb

notifications:
  irc: "irc.freenode.net#lisa-project"
  
branches:
  only:
    - master
